# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171109_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
